%YAML:1.0
# data
# the tum dataset directory
dataset_dir: /home/han/catkin_ws/src/data/rgbd_dataset_freiburg1_xyz

# camera intrinsics
# fr1
camera.fx: 525.3
camera.fy: 525.5
camera.cx: 319.5
camera.cy: 239.5

camera.depth_scale: 5000

# VO paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
